// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: sample
#ifndef GRPC_sample__INCLUDED
#define GRPC_sample__INCLUDED

#include "sample_generated.h"
#include "flatbuffers/grpc.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace sample {

class SampleService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Endpoint(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, flatbuffers::BufferRef<Response>* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::BufferRef<Response>>> AsyncEndpoint(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::BufferRef<Response>>>(AsyncEndpointRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< flatbuffers::BufferRef<Response>>* AsyncEndpointRaw(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Endpoint(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, flatbuffers::BufferRef<Response>* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::BufferRef<Response>>> AsyncEndpoint(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< flatbuffers::BufferRef<Response>>>(AsyncEndpointRaw(context, request, cq));
    }
  
   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< flatbuffers::BufferRef<Response>>* AsyncEndpointRaw(::grpc::ClientContext* context, const flatbuffers::BufferRef<SampleRoot>& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Endpoint_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
  
  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Endpoint(::grpc::ServerContext* context, const flatbuffers::BufferRef<SampleRoot>* request, flatbuffers::BufferRef<Response>* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Endpoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Endpoint() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Endpoint() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Endpoint(::grpc::ServerContext* context, const flatbuffers::BufferRef<SampleRoot>* request, flatbuffers::BufferRef<Response>* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEndpoint(::grpc::ServerContext* context, flatbuffers::BufferRef<SampleRoot>* request, ::grpc::ServerAsyncResponseWriter< flatbuffers::BufferRef<Response>>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef   WithAsyncMethod_Endpoint<  Service   >   AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Endpoint : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Endpoint() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Endpoint() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Endpoint(::grpc::ServerContext* context, const flatbuffers::BufferRef<SampleRoot>* request, flatbuffers::BufferRef<Response>* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace sample


#endif  // GRPC_sample__INCLUDED
